# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('good', models.TextField()),
                ('bad', models.TextField()),
                ('proposal', models.TextField()),
            ],
        ),
    ]
